/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgproc_ImgFeatureExtractionWrapper */

#ifndef _Included_imgproc_ImgFeatureExtractionWrapper
#define _Included_imgproc_ImgFeatureExtractionWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef imgproc_ImgFeatureExtractionWrapper_GLCM_DIM
#define imgproc_ImgFeatureExtractionWrapper_GLCM_DIM 16L
#undef imgproc_ImgFeatureExtractionWrapper_EOHDIM
#define imgproc_ImgFeatureExtractionWrapper_EOHDIM 37L
#undef imgproc_ImgFeatureExtractionWrapper_LBP_DIM
#define imgproc_ImgFeatureExtractionWrapper_LBP_DIM 256L
#undef imgproc_ImgFeatureExtractionWrapper_TOTAL_DIM
#define imgproc_ImgFeatureExtractionWrapper_TOTAL_DIM 521L
/*
 * Class:     imgproc_ImgFeatureExtractionWrapper
 * Method:    extractFeature
 * Signature: ([B[D)V
 */
JNIEXPORT void JNICALL Java_imgproc_ImgFeatureExtractionWrapper_extractFeature
  (JNIEnv *, jclass, jbyteArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
